import React from 'react';


   export  const PropertyIcons = [
        {
          id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba',
          title: 'Houses',
          emoji:'house',
        },
        {
          id: '3ac68afc-c605-48d3-a4f8-fbd91aa97f63',
          title: 'Apartment',
          emoji:'office',
        },
        {
          id: '58694a0f-3da1-471f-bd96-145571e29d72',
          title: 'Business Prospects',
          emoji:'department_store'
        },
        {
          id: '58694a0f-3da1-471f-bd96-145571e29d73',
          title: 'Lands',
          emoji:'snow_capped_mountain'
        },
        {
          id: '58694a0f-3da1-471f-bd96-145571e29d74',
          title: 'Resorts',
          emoji:'beach_with_umbrella'
        },
      ];


export const PropertyLists = [
        {
          id: 'e9f8g7h6-i5j4k3l2-m1n0o',
          propertyName: 'Willow Creek Manor',
          address: '1234 Birchwood Lane, Springfield, IL',
          price: '$2,350,000',
          image:require('../assets/properties/3d-house-interior-2021-12-09-02-44-03-utc.jpg'),
          gallery:[
            require('../assets/properties/Galleries/firsproperty_1.jpg'),
            require('../assets/properties/Galleries/firsproperty_2.jpg'),
            require('../assets/properties/Galleries/firsproperty_3.jpg'),
            require('../assets/properties/Galleries/firsproperty_4.jpg'),
            require('../assets/properties/Galleries/firsproperty_5.jpg'),
            require('../assets/properties/Galleries/firsproperty_6.jpg'),
            require('../assets/properties/Galleries/firsproperty_7.jpg'),
            require('../assets/properties/Galleries/firsproperty_8.jpg'),
            require('../assets/properties/Galleries/firsproperty_9.jpg'),
            require('../assets/properties/Galleries/firsproperty_10.jpg'),
          ],
          bed:'3',
          bathroom:'2',
          area:' 100 sqft',
          detail:"Vstupte do tohoto oázy moderního komfortu uprostřed historického centra. Tento útulný byt vám nabídne nejen výhled na malebné uličky, ale také spojení s bohatou historií tohoto města. S moderně zařízenou kuchyní a prostornou ložnicí s pohodlným nábytkem se tento byt stane ideálním útočištěm pro jednotlivce i páry. Pro ty, kteří chtějí mít veškeré pohodlí na dosah ruky a zároveň okusit atmosféru minulých dob.",
          },
          {
            id: 'a1b2c3d4-e5f6g7h8-i9j10k11',
            propertyName: 'Pine Ridge Cottage',
            address: '5678 Pine Street, Mountain View, CA',
            price: '$1,800,000',
            image: require('../assets/properties/house-2021-12-09-05-59-20-utc.jpg'),
            bed: '2',
            bathroom: '1.5',
            area: '85 sqft',
            detail:"Tato exkluzivní vila vám přináší nekonečný komfort a dechberoucí výhledy. S moderním a elegantním designem se interiér ladí s nádhernou terasou, kde můžete vychutnávat neuvěřitelné panoramatické pohledy na krajinu, lesy či moře. Soukromý bazén a prostorná zahrada umožní trávit čas venku s absolutním soukromím. Pro ty, kteří touží po špičkovém ubytování a nezapomenutelných pohledech.",
          },
          {
            id: 'x1y2z3w4-v5u6t7s8-r9q10p11',
            propertyName: 'Sunny Valley Villa',
            address: '910 Sunflower Road, Phoenix, AZ',
            price: '$3,500,000',
            image: require('../assets/properties/house-2021-12-09-05-59-23-utc.jpg'),
             gallery:[
            require('../assets/properties/Galleries/firsproperty_1.jpg'),
            require('../assets/properties/Galleries/firsproperty_2.jpg'),
            require('../assets/properties/Galleries/firsproperty_3.jpg'),
            require('../assets/properties/Galleries/firsproperty_4.jpg'),
            require('../assets/properties/Galleries/firsproperty_5.jpg'),
            require('../assets/properties/Galleries/firsproperty_6.jpg'),
            require('../assets/properties/Galleries/firsproperty_7.jpg'),
            require('../assets/properties/Galleries/firsproperty_8.jpg'),
            require('../assets/properties/Galleries/firsproperty_9.jpg'),
            require('../assets/properties/Galleries/firsproperty_10.jpg'),
          ],
            bed: '5',
            bathroom: '4',
            area: '300 sqft',
            detail:"Ideální domov pro rodiny, tento prostorný dům nabízí moderní vybavenou kuchyni, útulné pokoje a prostorné společenské prostory. Vstupte do velké udržované zahrady, která nabízí dostatek prostoru pro hry, zábavu a relaxaci. Bezproblémový život mimo městský ruch s veškerým pohodlím pro pohodlný rodinný život.",
          },
          {
            id: 'm1n2o3p4-q5r6s7t8-u9v10w11',
            propertyName: 'Oceanfront Retreat',
            address: '123 Ocean Avenue, Malibu, CA',
            price: '$5,750,000',
            image: require('../assets/properties/panorama-view-of-houses-2022-06-14-16-18-25-utc.jpg'),
             gallery:[
            require('../assets/properties/Galleries/firsproperty_1.jpg'),
            require('../assets/properties/Galleries/firsproperty_2.jpg'),
            require('../assets/properties/Galleries/firsproperty_3.jpg'),
            require('../assets/properties/Galleries/firsproperty_4.jpg'),
            require('../assets/properties/Galleries/firsproperty_5.jpg'),
            require('../assets/properties/Galleries/firsproperty_6.jpg'),
            require('../assets/properties/Galleries/firsproperty_7.jpg'),
            require('../assets/properties/Galleries/firsproperty_8.jpg'),
            require('../assets/properties/Galleries/firsproperty_9.jpg'),
            require('../assets/properties/Galleries/firsproperty_10.jpg'),
          ],
            bed: '4',
            bathroom: '3.5',
            area: '250 sqft',
            detail:"Pro milovníky netradičního a stylového bydlení je tento loft v industriálním stylu snem, který se stává skutečností. Otevřený koncept nabízí vysoké stropy, průmyslový design a moderní prvky. Velká okna zaplavují interiér světlem a vytvářejí unikátní atmosféru. Pro kreativní jedince, kteří chtějí bydlet nejen komfortně, ale i s výrazným stylem.",
          },
          {
            id: 'h1i2j3k4-l5m6n7o8-p9q10r11',
            propertyName: 'Rustic Mountain Cabin',
            address: '456 Cabin Lane, Aspen, CO',
            price: '$1,200,000',
            image: require('../assets/properties/rustic-house-2021-08-26-15-58-42-utc.jpg'),
             gallery:[
            require('../assets/properties/Galleries/firsproperty_1.jpg'),
            require('../assets/properties/Galleries/firsproperty_2.jpg'),
            require('../assets/properties/Galleries/firsproperty_3.jpg'),
            require('../assets/properties/Galleries/firsproperty_4.jpg'),
            require('../assets/properties/Galleries/firsproperty_5.jpg'),
            require('../assets/properties/Galleries/firsproperty_6.jpg'),
            require('../assets/properties/Galleries/firsproperty_7.jpg'),
            require('../assets/properties/Galleries/firsproperty_8.jpg'),
            require('../assets/properties/Galleries/firsproperty_9.jpg'),
            require('../assets/properties/Galleries/firsproperty_10.jpg'),
          ],
            bed: '2',
            bathroom: '1',
            area: '75 sqft',
            detail:"Užijte si relaxaci a pohodu v tomto útulném apartmánu, který je jen pár kroků od pláže. Zařízený s důrazem na komfort nabízí prostorný obývací pokoj, moderní kuchyň a útulnou ložnici. Ideální pro ty, kteří milují slunečné dny na pláži a večery plné klidu.",
          },
          {
            id: 'z1x2c3v4-b5n6m7q8-a9s10d11',
            propertyName: 'Cityscape Loft',
            address: '789 Urban Street, New York, NY',
            price: '$2,950,000',
            image: require('../assets/properties/traditional-wooden-houses-in-porvoo-finland-old-t-2022-02-02-05-07-36-utc.jpg'),
             gallery:[
            require('../assets/properties/Galleries/firsproperty_1.jpg'),
            require('../assets/properties/Galleries/firsproperty_2.jpg'),
            require('../assets/properties/Galleries/firsproperty_3.jpg'),
            require('../assets/properties/Galleries/firsproperty_4.jpg'),
            require('../assets/properties/Galleries/firsproperty_5.jpg'),
            require('../assets/properties/Galleries/firsproperty_6.jpg'),
            require('../assets/properties/Galleries/firsproperty_7.jpg'),
            require('../assets/properties/Galleries/firsproperty_8.jpg'),
            require('../assets/properties/Galleries/firsproperty_9.jpg'),
            require('../assets/properties/Galleries/firsproperty_10.jpg'),
          ],
            bed: '1',
            bathroom: '1.5',
            area: '120 sqft',
            detail:"Vítejte v moderním útočišti s impozantním výhledem na městskou kulisu. Tento byt spojuje elegantní design s praktičností pro pohodlný život ve městě. Otevřený obývací prostor a plně vybavená kuchyně tvoří srdce bytu, zatímco prosklená stěna vám umožní sledovat živou atmosféru města z pohodlí interiéru. Pro ty, kteří hledají spojení s městským pulzem a současně moderní a komfortní bydlení.",
          },
          {
            id: 'e9f8g7h6-i5j4k3l2-m1f0o',
            propertyName: 'Lakefront Oasis',
            address: '1010 Lakeshore Drive, Seattle, WA',
            price: '$4,200,000',
            image: require('../assets/properties/house-2021-12-09-05-59-23-utc.jpg'),
             gallery:[
            require('../assets/properties/Galleries/firsproperty_1.jpg'),
            require('../assets/properties/Galleries/firsproperty_2.jpg'),
            require('../assets/properties/Galleries/firsproperty_3.jpg'),
            require('../assets/properties/Galleries/firsproperty_4.jpg'),
            require('../assets/properties/Galleries/firsproperty_5.jpg'),
            require('../assets/properties/Galleries/firsproperty_6.jpg'),
            require('../assets/properties/Galleries/firsproperty_7.jpg'),
            require('../assets/properties/Galleries/firsproperty_8.jpg'),
            require('../assets/properties/Galleries/firsproperty_9.jpg'),
            require('../assets/properties/Galleries/firsproperty_10.jpg'),
          ],
            bed: '6',
            bathroom: '5',
            area: '400 sqft',
            detail:"Tato malebná chalupa vám poskytne únik z městského života a ponoření se do klidu a krásy přírody. S rustikálním designem a tradičními prvky vytváří autentickou atmosféru. S útulnými pokoji a prostorným obývacím prostorem s krbem je ideální pro odpočinek, pěší túry a únik do přírody.",
          },
         
      ];

 
